# Generated by Django 2.0.1 on 2018-01-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180107_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(default='Анонимно', max_length=50),
        ),
    ]
