# Generated by Django 2.0.1 on 2018-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
