# Generated by Django 2.0.1 on 2018-01-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
