# Generated by Django 2.0.1 on 2018-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20180109_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, height_field=900, null=True, upload_to='photo/', width_field=600),
        ),
    ]
