# Generated by Django 2.0.1 on 2018-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20180109_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field=900, upload_to='photo/', width_field=600),
        ),
    ]
