# Generated by Django 2.0.1 on 2018-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20180109_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='photo/no-img.jpg', upload_to='photo/'),
        ),
    ]
