# Generated by Django 2.0.1 on 2018-01-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20180109_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo2',
        ),
    ]
